### ISSUE TITLE
20230920 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/PY202309#1]
challenge/week3/dict_and_set	no enough comments

위 파일에 코멘트가 부족합니다.

**Comment by handonghoo** [comment]
뒤늦게 해당 파일에 코멘트 부족한것을 확인 하고 수정하였습니다. 
참고로 커밋메시지는 "issue solved 3" 입니다. 
체크해주셔서 감사합니다. 

- 한동호 학생 드림
