### ISSUE TITLE
20230927 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/PY202309#2]
challenge/week4/condition	no enough comments

위 파일에 주석이 없습니다.

**Comment by handonghoo** [comment]
지적해주셔서 감사합니다.
해당 이슈 체크하였으며 수정 완료 했습니다.
참고로 커밋 메시지 "Issue solved 2" 로 푸쉬 했습니다.

- 한동호 드림

2023년 9월 30일 (토) 오전 12:14, MisooKim2 ***@***.***>님이 작성:
