### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/PY202309#3]
### 없는 파일
- challenge/week7/todo.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in practice/week3/basic
    - 17:Statement seems to have no effect	smaple_list.sort
    - 20:Statement seems to have no effect	smaple_list.reverse
    - 25:Statement seems to have no effect	smaple_list.insert
    - 28:Statement seems to have no effect	smaple_list.reverse
        -  함수를 호출하기 위해서는 () 를 뒤에 붙여줘야 합니다. 위 코드처럼 작성한 경우 아무런 기능을 하지 않습니다. 위 코드에 함수를 호출하거나, 해당 라인을 지워주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week7/todo_extend
- Insufficient comments in practice/week6/function
- Insufficient comments in project/week8/search_engine

**Comment by handonghoo** [comment]
8189e3aca516d8c6c4b269079920fb553dace278
